
```{r}
install.packages("nycflights13")
install.packages("dplyr")
install.packages("ggplot2")

library(nycflights13)
library(dplyr)
library(ggplot2)
```

```{r}
View(flights)
View(airports)
View(planes)
View(airlines)
View(weather)
```

1. Inner-join

1.1
```{r}
flights %>%
  inner_join(planes, by = "tailnum")
```

1.2
```{r}
flights %>%
  inner_join(airlines, by="carrier")
```

1.3
```{r}
flights %>%
  inner_join(airports, by=c("origin" = "faa")) %>%
  inner_join(airports, by=c("dest" = "faa"))
```

1.4
```{r}
flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin"))

```

2.1
```{r}
flights %>%
  count(year, month, day) %>%
  filter(n>1000) %>%
  arrange(n)
```

2.2
```{r}
flights_selected <- flights %>%
  select(year:day, hour, origin, dest, tailnum, carrier, arr_delay, dep_delay)

```

2.3
```{r}
airlines %>%
  inner_join(flights_selected, by = "carrier") %>%
  select(-origin,-dest) %>%
  mutate(tot_delay =  arr_delay +  dep_delay)
```

2.4
```{r}
precip_delay <- flights %>%
  inner_join(weather, by=c("year","month","day","hour","origin")) %>%
  group_by(precip) %>%
  summarize(delay=mean(dep_delay, na.rm = TRUE)) %>%
  replace_na(list(delay, delay=0))

```

2.5
```{r}
ggplot(precip_delay, aes(x=delay, y=precip))+
  geom_point()
```

2.6
```{r}
flight <- flights %>%
  filter(year == 2013, month == 5, day == 10) %>%
  group_by(dest) %>%
  summarize(delay = mean(arr_delay, na.rm = TRUE))

flights_airports <- airports %>%
  inner_join(flight, by = c("faa"="dest"))
```

2.7
```{r}
ggplot(flights_airports, aes(x=lon, y=lat, color=delay, size=delay)) +
  geom_point()
```

2.8
```{r}
flights %>%
  inner_join(planes, by = "tailnum", suffix =  c("_flights", "_planes")) %>%
  transmute(tailnum, manufacturer, pi=(dep_delay + arr_delay)/air_time)
```

